### ISSUE TITLE
Upgrade Homeassistant 2025.10.2

### ISSUE THREAD

**Issue by djmanri3** [dave-code-ruiz/elkbledom#109]
When update Homeassistant and try to pair new device, appears this error:
`ERROR (MainThread) [custom_components.elkbledom.elkbledom] Error getting status: 'HaBleakClientWithServiceCache' object has no attribute 'get_services'`

Device before pair not working:
`Failed to perform the action light/turn_on. 'HaBleakClientWithServiceCache' object has no attribute 'get_services'`

**Comment by djmanri3** [comment]
Can you fix on Homeassistant 2025.10? thanks!

**Comment by llzzrrdd** [comment]
Issue with 1.2.6 when using Bluetooth Proxy (ESPHome)
Hi @dave-code-ruiz,
After upgrading to 1.2.6, my ELK-BLEDOM light stopped working. The entity showed the error:

"This entity is no longer being provided by the elkbledom integration"

My setup:

Home Assistant running in Docker
Bluetooth connectivity via ESPHome Bluetooth Proxy (ESP32)
Other BLE devices (like Airthings Wave+) work fine through the same proxy

What I tried:

Removed the orphaned entity
Removed and re-added the integration
The light was not discoverable anymore

Solution:
Downgrading to 1.2.5 via HACS immediately restored functionality. The light was discovered again and works perfectly.
Analysis:
It appears the new characteristics resolution method in 1.2.6 (replacing the deprecated get_services()) doesn't work correctly when the BLE connection goes through an ESPHome Bluetooth proxy. The HaBleakClientWithServiceCache behaves differently for proxied connections versus direct adapter connections.
Perhaps the fix needs conditional logic to handle both scenarios, or use the services property differently when a proxy is involved.
Happy to provide debug logs if needed.
